### PR TITLE
[WIP] Image optimisation

### PR DESCRIPTION
**Pull request by kaedroho**
Addresses #10

I plan on adding support for at least one optimiser for png and jpeg. The implemention will be done in a way that we can support multiple optimisers and choose one based on installation status/performance. It'll also provide extra operations to allow calling a specific optimiser directly (allowing the developer to pass in any custom arguments).

### CODE REVIEW

**Comment by bashu** [comment]
+1

**Comment by kaedroho** [comment]
After some testing, it doesn't look like optipng does much better than Pilllow itself.

One example PNG image I have is **410178 bytes** long (It's the first image to come up in a Google search for "Bender Rodriguez").
I ran optipng on this with it's default settings. This cut the image down to **98542 bytes**
But when I tried just loading and saving that image with Pillow (no operations performed), it is cut down to **94755 bytes**.

So in this case, Pillow on its own performs better than optipng!

**Comment by elalienx** [comment]
Hi! How about Huffman tables lossless jpeg optimisation that would reduce more kb because are used more on each webpage.
By the way excellent work on creating a wrapper to handle images on Wagtail!

**Comment by kaedroho** [comment]
Just been doing some investigation into JPEG image optimisation. Here are my results.

I tested jpegoptim and jpegtran on the JPEG images used on the torchbox.com website. I ran the following commands on each file:

``jpegoptim --strip-all --strip-iptc --strip-icc -d{out} {in}``
``jpegtran -optimize -progressive -outfile {out} {in}``

The output results were exactly the same, they both reduced 196M of images (2103 files) down to 129M of progressive JPEGs, which is a 35% average reduction!

**Comment by ddiazpinto** [comment]
It is not necessary to use another library to optimize images. PIL can do that pretty well. The problem is other. I have been testing the performance of this wrapper and the differences using PIL directly and I found some big differences in the results.

For example. I've tested a JPEG image of 1900x720 (424,5 KB) using by default 85 of quality. Using `fill-1920x400` tag in wagtail throws two operations: `FillOperation()` and `WidthHeightOperation`. The result is an image of 1900x386 and 282,6 KB. Using the same API function of PIL directly (`convert('RGB')`, `crop(Rect(0, 162, 1900, 558)`, `resize((1900, 396), Image.ANTIALIAS)` and `save(name, quality=85)`) the result is an image of 1900x396 (obviously) but 156,4 KB (~45% of improvement).

Using other options of `save()` function like `optimized=True` and `quality=False`, I get an image of 115,6 KB. This is about 60% of improvement.

Obviously, there is no appreciable differences between any of this images so, the conclusion is that something wrong it happens in an step before PIL, presumably with this library.

Any idea of what?

Anyway, I think that is necessary to allow this library to use all the options of each function of PIL, but this is a transversal matter that implies also Wagtail. How do you see it?

**Comment by elalienx** [comment]
Hi @ddiazpinto do you test if [Google Page Speed Insights](https://developers.google.com/speed/pagespeed/insights/) counts the PIL optimised images as compliant according to their test?
Thanks in advance.

**Comment by kaedroho** [comment]
That sounds very promising, I'll look into it when I next get time to work on this, thanks @ddiazpinto!

**Comment by kaedroho** [comment]
Implemented in #39

**Pull request closed without merging**
